### ISSUE TITLE
[python 3.8] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by Aufschlauer** [superna9999/pyfdt#18]
Hi,

I'm using pyfdt on python 3.8 (now - after distribution update to Linux Mint 20):
```bash
$ pip3 show pyfdt
Name: pyfdt
Version: 0.3
Summary: Python Flattened Device Tree Library
Home-page: https://github.com/superna9999/pyfdt
Author: Neil 'Superna' Armstrong
Author-email: superna9999@gmail.com
License: UNKNOWN
Location: /home/aufschlauer/.local/lib/python3.8/site-packages
Requires: 
Required-by: 
```
Now I got the issue when using pyfdt on python 3.8:
```python
$ python3 DeviceTree.py 
Traceback (most recent call last):
  File "DeviceTree.py", line 269, in <module>
    demo = Window()
  File "DeviceTree.py", line 160, in __init__
    dtb = FdtBlobParse(infile)
  File "/home/aufschlauer/.local/lib/python3.8/site-packages/pyfdt/pyfdt.py", line 1020, in __init__
    self.fdt_header = self.__extract_fdt_header()
  File "/home/aufschlauer/.local/lib/python3.8/site-packages/pyfdt/pyfdt.py", line 916, in __extract_fdt_header
    data = self.infile.read(header.size)
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte
```
I'm pretty sure that this has been working in the past with python 3.x. So I'm unsure whether is an issue of pyfdt or whether there are changes under the hood of python 3.8.

Any hints are welcome!

Thanks.

**Comment by ericzh123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Aufschlauer** [comment]
For whatever reason I was missing the correct opening options:
```python
with open(l_file, "rb") as infile:
```
The "open as binary" was missing
